### ISSUE TITLE
Añadir: Soporte para compilar multiples directorios

### ISSUE THREAD

**Issue by neverkas** [manu-projects/manu-cproject#1]
- [x] Cambiar estructura para soportar varios módulos
- [x] Compartir código entre módulos
- [x] Eliminar lógica repetida en el Makefile del raíz

**Comment by RaniAgus** [comment]
No entendí el issue 😕

**Comment by neverkas** [comment]
> No entendí el issue confused ¿Te referís a [algo así](https://github.com/RaniAgus/so-project-template/blob/release/v2.4/makefile#L1-L18)?

Buenas, exacto.
Similar a como venías haciendo con `so-project-template` tener varios módulos diferentes,
pero con la posibilidad de un Makefile genérico que se replique en cada directorio.

Una idea muy por encima sería hacer un `include` del Makefile base,
y que cada módulo sobreescriba las reglas/macros suponiendo que lo requiere.

**Comment by neverkas** [comment]
No se está contemplando el **compartir código entre proyectos** como si lo hace el de rani
https://github.com/RaniAgus/so-project-template/wiki/Compartir-c%C3%B3digo-entre-proyectos
