### ISSUE TITLE
Añadir: Entorno de prueba con contenedor Docker

### ISSUE THREAD

**Issue by neverkas** [manu-projects/manu-cproject#3]

**Comment by RaniAgus** [comment]
Mmm tengo entendido que Docker tiene limitaciones técnicas que hacen que se comporte distinto a una VM.

Tengo que chequearlo, estaría copado armar `.devcontainer`s, pero creo que quedaría por afuera del scope del makefile

**Comment by neverkas** [comment]
> Mmm tengo entendido que Docker tiene limitaciones técnicas que hacen que se comporte distinto a una VM.
> 
> Tengo que chequearlo, estaría copado armar `.devcontainer`s, pero creo que quedaría por afuera del scope del makefile

Buenas, por el momento lo resolvimos pasandole el comando del Makefile al contenedor con el `docker exec`,
pero está buena la idea. Voy a generar un nuevo issue para investigar más en detalle.

```Makefile
e exec:
	$(info Ejecutando aplicación del contenedor...)
	@docker exec $(IMAGE_NAME) make run

w watch:
	@docker run -it --rm --name $(IMAGE_NAME) \
		-v $(CURRENT_PATH)/$(SHARED_FOLDER):/home/$(SHARED_FOLDER) \
		--user $(UID):$(GID) \
		$(CONTAINER)
```
