### ISSUE TITLE
BUG: La carpeta .obj no existe

### ISSUE THREAD

**Issue by mbeorlegui** [manu-projects/manu-cproject#37]
Si la carpeta `.obj` dentro de `project/static` no existe, arroja el siguiente error:

```make
Mensajes del ensamblador:
Error fatal: no se puede crear .obj/lib_mylib.o: No existe el archivo o el directorio
make[2]: *** [../Makefile:22: .obj/lib_mylib.o] Error 1
make[1]: *** [../Makefile:22: .obj/sample1.o] Error 2
make: *** [Makefile:20: compile] Error 2
```

**Comment by neverkas** [comment]
Perfecto, gracias :)
Dejo agendado que tambien ocurre con el directorio `/bin` por tanto se debe volver a colocar los `.gitkeep`
y validar por Makefile que los directorios se creen en caso de no estar como segunda validacion.
