### ISSUE TITLE
Añadir: Registro de Logs por errores de compilación

### ISSUE THREAD

**Issue by neverkas** [manu-projects/manu-cproject#4]
- Por el momento que sólo los guarde en un `logs/`
- Recordar agregarlo en la regla de `clean`

```Makefile
DATE_FORMAT != date +%F-%H:%M             
LOG_PATH := logs 
LOG_CMD = >> $(LOG_PATH)/$(DATE_FORMAT).log 2>&1

$(DIR_BIN)/$(BIN): $(OBJ)
	$(info "Enlazamos los objetos ("$(notdir $^)") para crear el ejecutable ($(notdir $@)) en $(dir $@)")
	@$(CC) $(LDFLAGS) $(CFLAGS) $^ -o $@ $(LDLIBS) $(LOG_CMD)
```

Implementar en la siguiente linea
https://github.com/neverkas/manu-cproject/blob/033515edeca249d6ce3e070f5e487473483994eb/Makefile#L7

**Comment by RaniAgus** [comment]
Creo que podría traer problemas cuando se intenta compilar en un IDE como Eclipse. Quizás funcione usando [`tee`](https://www.geeksforgeeks.org/tee-command-linux-example/) en vez de pipes.

**Comment by neverkas** [comment]
> Creo que podría traer problemas cuando se intenta compilar en un IDE como Eclipse. Quizás funcione usando [`tee`](https://www.geeksforgeeks.org/tee-command-linux-example/) en vez de pipes.

Genial, desconocía la incompatibilidad con eclipse después pruebo e investigo usando ese comando
