### ISSUE TITLE
Bug: make memcheck

### ISSUE THREAD

**Issue by AlejoGol** [manu-projects/manu-cproject#44]
![image](https://user-images.githubusercontent.com/44068287/160305066-99ee85e1-5856-4299-ad0a-1b93bcf023c2.png)
make memcheck funciona desde la carpeta del modulo, pero no desde la raiz

**Comment by neverkas** [comment]
Perfecto, habria que terminar de validar si tambien ocurre en la rama https://github.com/manu-projects/manu-cproject/tree/feature/static-shared-libs
