### ISSUE TITLE
Añadir: Registro de logs para Valgrind

### ISSUE THREAD

**Issue by neverkas** [manu-projects/manu-cproject#5]
- Contemplar el mismo comportamiento que #4 
- Mantener una ruta separada para estos errores

**Comment by RaniAgus** [comment]
Quizás se resuelva exponiendo una variable en los [settings.mk](https://github.com/RaniAgus/so-project-template/blob/main/project/settings.mk#L16-L17) para que el usuario defina si quiere guardar el output en un log file y en qué ruta.

**Comment by neverkas** [comment]
> Quizás se resuelva exponiendo una variable en los [settings.mk](https://github.com/RaniAgus/so-project-template/blob/main/project/settings.mk#L16-L17) para que el usuario defina si quiere guardar el output en un log file y en qué ruta.

Perfecto, me encanta, se me había olvidado esos flags para `memcheck`
