### ISSUE TITLE
Añadir: Configuración automática para Vscode

### ISSUE THREAD

**Issue by neverkas** [manu-projects/manu-cproject#6]
- Generar los archivos de configuración en .vscode para cada módulo
- Agregar los datos con macros

**Comment by RaniAgus** [comment]
Yo prefiero hacerlo en un tutorial en la guía, así no lo sobrecargamos de archivos (si un grupo quiere usar Eclipse, esa carpeta estaría de más). Aparte el tutorial permite explicar un toque mejor cómo funciona cada atributo que le agregan al JSON. Sino sería una "solución mágica" y puede traer confusiones.

**Comment by neverkas** [comment]
> Yo prefiero hacerlo en un tutorial en la guía, así no lo sobrecargamos de archivos (si un grupo quiere usar Eclipse, esa carpeta estaría de más). Aparte el tutorial permite explicar un toque mejor cómo funciona cada atributo que le agregan al JSON. Sino sería una "solución mágica" y puede traer confusiones.

Coincido con la sobrecarga de ficheros
